version: "3.3"

services:
  library:
    restart: always
    image: sameersbn/postgresql:10-2
    environment:
      - PG_TRUST_LOCALNET=true
      - DB_NAME=evacc
      - DB_USER=admin
      - DB_PASS=admin123
      - PG_RUNDIR=/run/postgres
      - PG_LOGDIR=/var/log/postgres
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql
      - logs:/var/log/postgresql
#  traefik:
#    image: "traefik:v2.6"
#    container_name: "traefik"
#    command:
#      - "--providers.docker=true"
#      - "--providers.docker.exposedbydefault=false"
#      - "--entrypoints.web.address=:80"
#      - "--entrypoints.websecure.address=:443"
#      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
#      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
#    ports:
#      - "80:80"
#      - "443:443"
#    volumes:
#      - "/var/run/docker.sock:/var/run/docker.sock:ro"
#  keycloak:
#    restart: always
#    image: quay.io/keycloak/keycloak:17.0
#    environment:
#      - KEYCLOAK_ADMIN=keycloak
#      - KEYCLOAK_ADMIN_PASSWORD=keycloak
#      - KC_HOSTNAME=auth.localhost
#      - KC_DB=dev-mem
#    labels:
#      - "traefik.enable=true"
#      - "traefik.http.routers.keycloak.rule=Host(`auth.localhost`)"
#      - "traefik.http.routers.keycloak.entrypoints=websecure"
#      - "traefik.http.routers.keycloak.tls=true"
#      - "traefik.http.services.keycloak.loadbalancer.server.port=8080"
#    entrypoint: /opt/keycloak/bin/kc.sh start-dev --proxy edge --hostname auth.localhost
volumes:
  data:
  logs: